### Remote runs
### Local runs
```{r Load example data}
huntington_disease_up <- as.data.frame.matrix(read.delim("matrix-hd-up.dat", header = FALSE))

huntington_disease_down <- as.data.frame.matrix(read.delim("matrix-hd-down.dat", header = FALSE))

huntington_list <- list(huntington_disease_up, huntington_disease_down)

graph_file = system.file("extdata", "sampleNetwork.sif", package="Rkpm")
```

```{r With perturbation}
# Use perturbation
kpm_options(execution = "Local", strategy = "INES", algorithm ="Greedy",l_min=5,
            k_min = 2, perturbation_technique ="nodeswap",
            with_perturbation = TRUE,
            perturbation_start = 10,
            perturbation_step = 10,
            perturbation_max = 20,
            graphs_per_step = 1,
            resource_folder = system.file(package = "Rkpm", "extdata/"),
            properties_file = system.file(package = "Rkpm", "kpm.properties"))

kpm(graph_file = graph_file, indicator_matrices  = huntington_disease_up)
settings::reset(kpm_options)
```

```{r Combine multiple datasets}
# Combine multiple datasets:
kpm_options(execution = "Local", 
            strategy = "GLONE",
            algorithm ="Greedy",
            l_min=c(5,2),
            resource_folder = system.file(package = "Rkpm", "extdata/"))
kpm(graph_file = graph_file, indicator_matrices  = huntington_list)
settings::reset(kpm_options)
```

```{r Batch run}
# Use ranged values with batch
kpm_options(execution = "Local",
            strategy = "INES",
            algorithm ="Greedy",
            l_min=c(1,1),
            l_step=c(2,2),
            l_max=c(3,3),
            k_min = 1,
            k_step = 2,
            k_max = 3,
            use_range_k = TRUE,
            use_range_l = TRUE,
            resource_folder = system.file(package = "Rkpm", "extdata/"))
kpm(graph_file = graph_file, indicator_matrices  = huntington_list)
settings::reset(kpm_options)
```





