---
title: "Rkpm - Format of the input files"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{input_files_format}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Graph file 
**Description:** The file containing all the interactions of the protein interaction network.

**For:** `Remote` and `Local` execution.

**Format:** Values are seperated with **TAB** and lines with **NEWLINE**. Provide file **without the header** (first row). The file must be in .sif format and has the following structure:

| NODE1 | INTERACTION_TYPE | NODE2  |
|------:|:----------------:|:------:|
| 112   |  pp              |  342   |
| 12    |  pp              |  42    |
| ...                               |
| ...                               |


**For local execution:** If you want change the seperator to a comma or space or use a header you will have to define this in the kpm_properties file. You can do that by using `edit(file = system.file(package = "Rkpm", "kpm.properties"))` and changing **graph_file_has_header**, **graph_file_separator**.

**Usage:**  Once your file has the correct format provide it to Rkpm as string with the **path** to the file:
`kpm(graph_file = PATH_TO_YOUR_NETWORK, indicator_matrices)`

## Matrix file/s
**Description:** Files containing matrices from the expression studies.
KPM can take as input **several** of these files, which can be defined either through R (example in `vignette("Rkpm")`) 
or in the DATASETS file (see below). 

**For:** `Remote` and `Local` execution.

**Format:** Values are seperated with **TAB** and lines with **NEWLINE**. Provide file **without the header** (first row).

| GENE_ID | CASE1 | CASE2  | ...  | CASEX  |
|--------:|:-----:|:------:|:----:|:------:|
| 10203   |  1    |  0     | ...  | 1      |
| 3232    |  0    |  0     | ...  | 1      |      
| ...                                      |
| ...                                      |

**For local execution:** If you want change the seperator to a comma or space or use a header you will have to define this in the kpm_properties file. You can do that by using `edit(file = system.file(package = "Rkpm", "kpm.properties"))` and changing **matrix_files_have_header**, **matrix_files_separator**.

**Usage:** Once your file has the correct format provide it to Rkpm as **path** or as `data.frame`. Or as a list of both. Use `vignette("Rkpm")` for examples.


## Dataset file 
**Description:** This file contains the paths to each individual
indicator matrix file and it's corresponding L parameter .

**For:** `Local` execution.

**Format:** Values are seperated with **TAB** and lines with **NEWLINE**. Provide file **without the header** (first row).

| ID   | L                | PATH                     |
|-----:|:----------------:|:------------------------:|
| 1    |  10              |  path/to/matrix1.txt     |
| 2    |  15              |   path/to/matrix2.txt    |
| ...                                                |
| ...                                                |

**For local execution:** If you want change the seperator to a comma or space or use a header you will have to define this in the kpm_properties file. You can do that by using `edit(file = system.file(package = "Rkpm", "kpm.properties"))` and changing **datasets_file_separator** , **datasets_file_has_header**.

**Usage:**  Once your file has the correct format override the **path** in the kpm.properties file by using `edit(file = system.file(package = "Rkpm", "kpm.properties"))` and changing **datasets_file** to the correct path.

## Positive/Negative list file 
**Description:** These are optional files that contain
a list of genes that will be given high **(POSITIVE list)** or low **(NEGATIVE list)**
priority when searching for pathways.

**For:** `Local` execution.

**Format:** After every line a **NEWLINE** is used and the file is provided **without the header**. 

| NODE_ID   |
|----------:|
| 11423     | 
| 1213      | 
| ...       |            
| ...       |


**Usage:** Once your file has the correct format override the **path** in the kpm.properties file by using `edit(file = system.file(package = "Rkpm", "kpm.properties"))` and changing **negative_file** or **positive_file**.

