library("rJava")
library("rjson")
library("RCurl")
library("roxygen2")
library("settings")
library("testthat")
library("devtools")
library("renv")
library("formatR")  # formatR::tidy_dir('R')
library("lintr")  # lintr::lint_package()
library(foreach)
